### ISSUE TITLE
When pytorch version release☺

### ISSUE THREAD

**Issue by AceCoooool** [yeezhu/SPN.pytorch#1]
The idea is pretty cool~ 
And when the pytorch version will release?~

**Comment by yeezhu** [comment]
@AceCoooool 
Thanks for your interest in our work!
The pytorch code is under testing, we will release it at the latest before the meeting(Oct.20).

**Comment by yeezhu** [comment]
@AceCoooool 
PyTorch implementation of SPN is available now.
