### ISSUE TITLE
demo/evaluation misses __init__.py

### ISSUE THREAD

**Issue by vadimkantorov** [yeezhu/SPN.pytorch#13]
I'm getting an error on line [`from evaluation.SP_GoogLeNet import SP_GoogLeNet`](https://github.com/yeezhu/SPN.pytorch/blob/master/demo/experiment/util.py#L14). Adding `__init__.py` to `demo/evaluation` fixes it.

**Comment by yeezhu** [comment]
I have fixed it, thank you!
