### ISSUE TITLE
about the code in `SP_Generate` function

### ISSUE THREAD

**Issue by zimenglan-sysu-512** [yeezhu/SPN.pytorch#15]
hi @yeezhu 
I want to rewrite the main code of spn in caffe, so i follow the code, but i have a little about the pytorch, so can you help me that what those two [THCTensor_(sumall)](https://github.com/yeezhu/SPN.pytorch/blob/master/spnlib/spn/src/generic/SoftProposalGenerator.cu#L114) and [THCTensor_(normall)](https://github.com/yeezhu/SPN.pytorch/blob/master/spnlib/spn/src/generic/SoftProposalGenerator.cu#L125) functions do？
  
thanks

**Comment by yeezhu** [comment]
@zimenglan-sysu-512 
You can check [here](https://github.com/pytorch/pytorch/blob/00d2befba11a1e9c85146a4470721eb75596d5b7/aten/src/THC/generic/THCTensorMathReduce.cu#L262).

**Comment by zimenglan-sysu-512** [comment]
hi @yeezhu ,
thanks for providing it.
