### ISSUE TITLE
Training on new dataset

### ISSUE THREAD

**Issue by Supersak80** [yeezhu/SPN.pytorch#17]
Hi @yeezhu,

Are you able to provide a generic script that allows for training on a custom dataset other than PASCAL VOC, assuming that the images for each class are stored in their respective folders?

Thanks,
Sam

**Comment by yeezhu** [comment]
@Supersak80 
See [here](https://github.com/durandtibo/wildcat.pytorch/blob/master/wildcat/mit67.py),  a demo dataloader for MITIndoor67.
