### ISSUE TITLE
Transfer matrix definition

### ISSUE THREAD

**Issue by vadimkantorov** [yeezhu/SPN.pytorch#24]
In the paper and the code you define D as: `D(ij, pq) = ||u_ij - u_pq|| * exp(-((i - p)**2 + (j - q)**2)/(2 * sigma**2))` where `u` is the features tensor, and `i,j,p,q` are coordinates of two feature vectors.

The first term is dissimilarity (when it's large, features are very dissimilar), the second is similarity (when it's large, features are very close geometrically). Please correct me if I'm getting it wrongly.

During update of objectness vector:
`M_i = \sum_j M_j * D_ji`, i.e. `M_i` will have high objectness if locations `j` have high objectness and are dissimilar to `i`.

Does it make sense to mix dissimilarity and similarity?

Thanks!

**Comment by yeezhu** [comment]
D represents dissimilarity between receptive fields, and the random walker accumulates mass at nodes that have high dissimilarity with other nodes, thus salient object regions get high objectness confidence other than backgrounds. The normalized spatial distance is a kind of weight for feature dissimilarity.

**Comment by vadimkantorov** [comment]
I kind of understand now. Thanks!

Can you please clarify this line https://github.com/yeezhu/SPN.pytorch/blob/master/spnlib/spn/src/generic/SoftProposalGenerator.cu#L117 (kernel_(UpdateProposal))?
If I understand well, it does `M = M + DM` (instead of `M = DM` in the paper). Am I right?

**Comment by yeezhu** [comment]
In [line 100](https://github.com/yeezhu/SPN.pytorch/blob/f8ebdca128ce6b550d090b45dae7ef43d54d00e1/spnlib/spn/src/generic/SoftProposalGenerator.cu#L100) `proposalBuffer = DM - M`. 
So it does `M = M + DM - M = DM` in [line 117](https://github.com/yeezhu/SPN.pytorch/blob/f8ebdca128ce6b550d090b45dae7ef43d54d00e1/spnlib/spn/src/generic/SoftProposalGenerator.cu#L117).

**Comment by vadimkantorov** [comment]
Got it. Thanks!
