### ISSUE TITLE
SP_GoogleNet_ImageNet may not exist

### ISSUE THREAD

**Issue by wangbo2016** [yeezhu/SPN.pytorch#29]
I want to download the model "SP_GoogleNet_ImageNet", but it no longer exists

**Comment by yeezhu** [comment]
See https://drive.google.com/open?id=1Yn0ML48-7MJdgxGgf-d_hVeUoOLD6zk2

**Comment by wangbo2016** [comment]
> See https://drive.google.com/open?id=1Yn0ML48-7MJdgxGgf-d_hVeUoOLD6zk2

Thank you very much!
