### ISSUE TITLE
Which python version?

### ISSUE THREAD

**Issue by JingyunLiang** [yeezhu/SPN.pytorch#3]
I tried python3.5.4 & python3.6.2, but failed to install torchnet:
```
  Could not find a version that satisfies the requirement torchnet (from versions: )
No matching distribution found for torchnet
```

**Comment by MichaelLiang12** [comment]
modify title

**Comment by yeezhu** [comment]
@MichaelLiang12 
It seems not the python version issues, please check here: https://github.com/pytorch/tnt

**Comment by JingyunLiang** [comment]
Yes, torchnet is not on pypi yet. you have to install from source for now. Ref to [https://github.com/pytorch/tnt/issues/9](https://github.com/pytorch/tnt/issues/9)
```
pip install git+https://github.com/pytorch/tnt.git@master
```
Thank you.
